### ISSUE TITLE
Version 1.5.0 : Question about PDF/A and PdfXConformanceException

### ISSUE THREAD

**Issue by svareg** [openoereb/pyramid_oereb#876]
Hello,

While generating a PDF extract, I'm getting the following error:

```
Error while processing request:
com.lowagie.text.pdf.PdfXConformanceException: The /SMask key is not allowed in images.
```

As described here https://openoereb.github.io/pyramid_oereb/doc/changes.html#mapfish-print-pdf-a-conformance, I changed all my static pictures to 24bits pngs (without alpha-channel)

But it doesn't seems to be sufficient.
Do ALL the images need to be without transparency?
I mean : the legend icons, the images that comes from WMS queries (with parameter transparency=true), ...etc ?

If that's the case, there will be a problem, because the icons we get in the transfert structure from the confederation contains b64 encoded picture with transparency, for example for baulininen :
![test_img2](https://user-images.githubusercontent.com/36037102/59761107-3431ba00-9294-11e9-9553-ded8c0413f30.png)

Did I miss something here?
Thanks!
Guillaume

**Comment by svareg** [comment]
When I do as documented and remove the net.sf.jasperreports.export.pdfa.conformance parameter from pdfextract.jrxml, the PDF is generated correctly.

Why did we implement this? 
Do we really need this PDF/A compliance ?
Is it a official state recommendation?

Thanks,
Guillaume.

**Comment by voisardf** [comment]
yes it's a legal requirement

**Comment by svareg** [comment]
Hi François,

Ok , I understand.

But the main problem is : The confederation uses images with transparency for legend icons in the transfert-model. 
This means we must generate a valid PDF/A document without transparent pictures, but we only have icons with transparency for the federal themes.

I think there's an inconsistency there, and for now we won't be able to generate any valid PDF/A document.
Is it possible to report this to the confederation ?

**Comment by voisardf** [comment]
Yes sure. I can report this. I do not think that the confederation has a major issue with the fact that for now we are not PDF/A compliant - But the issue is on the Jasper Report side unfortunately... so the solution to just remove the tag until Jasper handles it as it should is probably the way to go.

**Comment by svareg** [comment]
I'm not sure I understand what you say.
For me, the issue is not on the Jasper Report side.

The standard PDF/A does not allow transparency. Then Jasper do it correctly for me.
Is the problem not, that the confederation has transparent pictures in its data?

**Comment by voisardf** [comment]
well, transparency depends on the version: https://en.wikipedia.org/wiki/PDF/A
a-1 does not allow it, A-2 does, but there are all kind of restrictions with that format... I think in any case it's a good idea to report this points back to the confederation as the group was not aware of all.

**Comment by voisardf** [comment]
I asked the federal office this morning how to handle this problem, as the specification defines a format which is not compatible with the delivered data (even those produced by the federal offices).

The topic will be discussed and solved in the group that has just started with the revision of the technical specifications. - A solution will be found for 2020.

**Comment by svareg** [comment]
Hello everyone,

I've just migrate to the version 1.8.1, and noticed that this problem is still relevant.
Did I miss some information about this ?

If this isn't any solution yet, I suggest that we comment the concerned line in the print templates: https://github.com/openoereb/pyramid_oereb_mfp/blob/master/print-apps/oereb/pdfextract.jrxml#L8

This will avoid having the same problem each time during migrations.
What do you think?

**Comment by vvmruder** [comment]
I will have a deeper look on that with François next Friday.

**Comment by jwkaltz** [comment]
@voisardf @vvmruder @svareg as summarized in #1210, the plan is to stay with PDF/a-1 in pyramid_oereb version 2. So transparent images will still not be allowed.
Is this a problem regarding the data delivery from the federation? Should we plan something for that (e.g. more discussions with the federation; or transformation of their images within pyramid_oereb; or ...)

**Comment by voisardf** [comment]
@jwkaltz I think it is ok if we generate the PDF as before (PDF/a-1). But I'll clarify the question with the confederation.
Regarding your comment to finance/contribute to a PDF/A-2 support in Jasper I wonder what you think how complicated or expensive that would be?

**Comment by jwkaltz** [comment]
> @jwkaltz I think it is ok if we generate the PDF as before (PDF/a-1). But I'll clarify the question with the confederation.
> Regarding your comment to finance/contribute to a PDF/A-2 support in Jasper I wonder what you think how complicated or expensive that would be?

@voisardf not easy, for sure. I suppose that for someone that implemented PDF/A-1 in JasperReports it might be feasible in a few days, but for anybody else...? 
I opened an issue in the JasperReports projects, maybe we will get some insights.

**Comment by remyguillaume** [comment]
Hi @voisardf @vvmruder @jwkaltz,

As a summary:
- Removing PDF/A compliance is not possible today, because PDF/A compliance is a federal requirement.
- Staying with PDF/A-1 is not possible today, because th confederation delivers transparent pictures in their data.
- Migrating to PDF/A-2 is not possible today, because the current version of MFP/Jaspersoft does not support this standard.

I don't see a lot solutions...
- Tell the confederation to update their data (should be easy to do, but as this ticket is opened since 2 years now, I think they don't want to do that.)
- Contribute to a PDF/A-2 support in Jasper (doesn't seem easy to do, and can be a bit expensive).

My proposal would be to analyze how much will cost the support of PDF/A-2 in Jasper, because it seems that it is the best solution for the future of pyramid_oereb.

**Comment by vvmruder** [comment]
Should be solved (mail i.Rey 03.11.2022). Reopen of not.
